name: Publish Website

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish:
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v13
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install nanoc
        run: |
          gem install nanoc kramdown-parser-gfm rouge
      - name: "Compile documentation"
        run: "sbt 'set ThisBuild / tlFatalWarningsInCi := false' documentation/mdoc"
      - name: "Build site"
        run: "sbt 'set ThisBuild / tlFatalWarningsInCi := false' makeSite"
      - name: "Install stork"
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: stork-search --locked
      - name: "Build search index"
        run: 'stork build --input target/site/index.toml --output target/site/index.st'
      - uses: actions/upload-artifact@v3
        with:
          name: site
          path: target/site/
      - name: "Publish site"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site
          exclude_assets: '.github,**/index.toml'
